//   1 BOOL_AND     : XXX
//   6 BOOL_NEGATE  : XX
//   1 BOOL_OR      : XXX
//   1 BRANCHIND    : X
//   2 BRANCH       : X
//   2 CALLOTHER    : X
//   3 CALLOTHER    : XX
//   1 CALLOTHER    : XXXXXX
//   3 CALL         : X
//   4 CBRANCH      : XX
//  85 COPY         : XX
//  38 INT_ADD      : XXX
// 320 INT_AND      : XXX
//  14 INT_CARRY    : XXX
//  51 INT_EQUAL    : XXX
// 242 INT_LEFT     : XXX
//   9 INT_LESS     : XXX
//   3 INT_NEGATE   : XX
//  19 INT_NOTEQUAL : XXX
// 241 INT_OR       : XXX
//  40 INT_RIGHT    : XXX
//   2 INT_SRIGHT   : XXX
//  32 INT_SUB      : XXX
//   3 INT_XOR      : XXX
//   2 INT_ZEXT     : XX
//  28 LOAD         : XXX
//  22 MULTIEQUAL   : X
//   3 RETURN       : X
//  20 STORE        : XXX

//   1 BOOL_AND 0     : CONST_SPACEID CONST_REAL CONST_REAL
//   1 BOOL_AND 1     : CONST_SPACEID CONST_REAL CONST_REAL
//   1 BOOL_AND 2     : CONST_SPACEID CONST_REAL CONST_REAL
//   6 BOOL_NEGATE 0  : CONST_SPACEID CONST_REAL CONST_REAL
//   2 BOOL_NEGATE 1  : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   4 BOOL_NEGATE 1  : CONST_SPACEID CONST_REAL CONST_REAL
//   1 BOOL_OR 0      : CONST_SPACEID CONST_REAL CONST_REAL
//   1 BOOL_OR 1      : CONST_SPACEID CONST_REAL CONST_REAL
//   1 BOOL_OR 2      : CONST_SPACEID CONST_REAL CONST_REAL
//   2 BRANCH 1       : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   1 BRANCHIND 1    : CONST_SPACEID CONST_REAL CONST_REAL
//   3 CALL 1         : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   1 CALLOTHER 0    : CONST_SPACEID CONST_REAL CONST_REAL
//   6 CALLOTHER 1    : CONST_SPACEID CONST_REAL CONST_REAL
//   4 CALLOTHER 2    : CONST_SPACEID CONST_REAL CONST_REAL
//   1 CALLOTHER 3    : CONST_SPACEID CONST_REAL CONST_REAL
//   1 CALLOTHER 4    : CONST_SPACEID CONST_REAL CONST_REAL
//   1 CALLOTHER 5    : CONST_SPACEID CONST_REAL CONST_REAL
//   2 CBRANCH 1      : CONST_CURSPACE CONST_NEXT CONST_CURSPACE_SIZE
//   2 CBRANCH 1      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   2 CBRANCH 2      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   2 CBRANCH 2      : CONST_SPACEID CONST_REAL CONST_REAL
//  19 COPY 0         : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//  66 COPY 0         : CONST_SPACEID CONST_REAL CONST_REAL
//  23 COPY 1         : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   5 COPY 1         : CONST_HANDLE CONST_HANDLE CONST_REAL
//  57 COPY 1         : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_ADD 0      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//  37 INT_ADD 0      : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_ADD 1      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//  37 INT_ADD 1      : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_ADD 2      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   3 INT_ADD 2      : CONST_HANDLE CONST_HANDLE CONST_REAL
//   2 INT_ADD 2      : CONST_SPACEID CONST_REAL CONST_HANDLE
//  32 INT_ADD 2      : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_AND 0      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   1 INT_AND 0      : CONST_SPACEID CONST_REAL CONST_HANDLE
// 318 INT_AND 0      : CONST_SPACEID CONST_REAL CONST_REAL
//   3 INT_AND 1      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   3 INT_AND 1      : CONST_HANDLE CONST_HANDLE CONST_REAL
// 314 INT_AND 1      : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_AND 2      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   1 INT_AND 2      : CONST_HANDLE CONST_HANDLE CONST_REAL
//   1 INT_AND 2      : CONST_SPACEID CONST_REAL CONST_HANDLE
// 317 INT_AND 2      : CONST_SPACEID CONST_REAL CONST_REAL
//  14 INT_CARRY 0    : CONST_SPACEID CONST_REAL CONST_REAL
//  14 INT_CARRY 1    : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_CARRY 2    : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   3 INT_CARRY 2    : CONST_HANDLE CONST_HANDLE CONST_REAL
//  10 INT_CARRY 2    : CONST_SPACEID CONST_REAL CONST_REAL
//  51 INT_EQUAL 0    : CONST_SPACEID CONST_REAL CONST_REAL
//  51 INT_EQUAL 1    : CONST_SPACEID CONST_REAL CONST_REAL
//  51 INT_EQUAL 2    : CONST_SPACEID CONST_REAL CONST_REAL
// 242 INT_LEFT 0     : CONST_SPACEID CONST_REAL CONST_REAL
// 242 INT_LEFT 1     : CONST_SPACEID CONST_REAL CONST_REAL
//   6 INT_LEFT 2     : CONST_HANDLE CONST_HANDLE CONST_REAL
// 236 INT_LEFT 2     : CONST_SPACEID CONST_REAL CONST_REAL
//   9 INT_LESS 0     : CONST_SPACEID CONST_REAL CONST_REAL
//   9 INT_LESS 1     : CONST_SPACEID CONST_REAL CONST_REAL
//   9 INT_LESS 2     : CONST_SPACEID CONST_REAL CONST_REAL
//   3 INT_NEGATE 0   : CONST_SPACEID CONST_REAL CONST_REAL
//   3 INT_NEGATE 1   : CONST_SPACEID CONST_REAL CONST_REAL
//  19 INT_NOTEQUAL 0 : CONST_SPACEID CONST_REAL CONST_REAL
//  19 INT_NOTEQUAL 1 : CONST_SPACEID CONST_REAL CONST_REAL
//  19 INT_NOTEQUAL 2 : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_OR 0       : CONST_HANDLE CONST_HANDLE CONST_HANDLE
// 240 INT_OR 0       : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_OR 1       : CONST_HANDLE CONST_HANDLE CONST_HANDLE
// 240 INT_OR 1       : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_OR 2       : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   1 INT_OR 2       : CONST_HANDLE CONST_HANDLE CONST_REAL
// 239 INT_OR 2       : CONST_SPACEID CONST_REAL CONST_REAL
//  40 INT_RIGHT 0    : CONST_SPACEID CONST_REAL CONST_REAL
//  40 INT_RIGHT 1    : CONST_SPACEID CONST_REAL CONST_REAL
//  40 INT_RIGHT 2    : CONST_SPACEID CONST_REAL CONST_REAL
//   2 INT_SRIGHT 0   : CONST_SPACEID CONST_REAL CONST_REAL
//   2 INT_SRIGHT 1   : CONST_SPACEID CONST_REAL CONST_REAL
//   2 INT_SRIGHT 2   : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_SUB 0      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//  31 INT_SUB 0      : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_SUB 1      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//  31 INT_SUB 1      : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_SUB 2      : CONST_SPACEID CONST_REAL CONST_HANDLE
//  31 INT_SUB 2      : CONST_SPACEID CONST_REAL CONST_REAL
//   3 INT_XOR 0      : CONST_SPACEID CONST_REAL CONST_REAL
//   3 INT_XOR 1      : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_XOR 2      : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   1 INT_XOR 2      : CONST_HANDLE CONST_HANDLE CONST_REAL
//   1 INT_XOR 2      : CONST_SPACEID CONST_REAL CONST_REAL
//   2 INT_ZEXT 0     : CONST_SPACEID CONST_REAL CONST_REAL
//   1 INT_ZEXT 1     : CONST_HANDLE CONST_HANDLE CONST_REAL
//   1 INT_ZEXT 1     : CONST_SPACEID CONST_REAL CONST_REAL
//   2 LOAD 0         : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//  26 LOAD 0         : CONST_SPACEID CONST_REAL CONST_REAL
//  28 LOAD 1         : CONST_SPACEID CONST_SPACEID CONST_REAL
//  28 LOAD 2         : CONST_SPACEID CONST_REAL CONST_REAL
//  22 MULTIEQUAL 1   : CONST_SPACEID CONST_REAL CONST_REAL
//   3 RETURN 1       : CONST_SPACEID CONST_REAL CONST_REAL
//  20 STORE 1        : CONST_SPACEID CONST_SPACEID CONST_REAL
//  20 STORE 2        : CONST_SPACEID CONST_REAL CONST_REAL
//   2 STORE 3        : CONST_HANDLE CONST_HANDLE CONST_HANDLE
//   1 STORE 3        : CONST_HANDLE CONST_HANDLE CONST_REAL
//   3 STORE 3        : CONST_SPACEID CONST_NEXT CONST_REAL
//  14 STORE 3        : CONST_SPACEID CONST_REAL CONST_REAL

enum Pcode {
    BOOL_AND,
    BOOL_NEGATE,
    BOOL_OR,
    BRANCH,
    BRANCHIND,
    CALL,
    CALLOTHER,
    CBRANCH,
    COPY,
    INT_ADD,
    INT_AND,
    INT_CARRY,
    INT_EQUAL,
    INT_LEFT,
    INT_LESS,
    INT_NEGATE,
    INT_NOTEQUAL,
    INT_OR,
    INT_RIGHT,
    INT_SUB,
    INT_XOR,
    LOAD,
    MULTIEQUAL,
    RETURN,
    STORE,
}
